### PR TITLE
Release branch for 1.5.0

### PR DESCRIPTION
**Pull request by bhati-pradeep**
Automation and bug fixes related to foundation and foundation central

### CODE REVIEW

**Comment by bhati-pradeep** [comment]
/ok-to-test
>Acceptance test run status: failure
>Current line coverage (49.7) is below threshold (50). Kindly add more acceptance tests.

**Comment by bhati-pradeep** [comment]
/ok-to-test
>Acceptance test run status: failure
>Line code coverage is 61.8

**Comment by abhimutant** [comment]
/ok-to-test
>Acceptance test run status: failure
>Line code coverage is 61.7

**Comment by bhati-pradeep** [comment]
TestAccFoundationIPMIConfigResource Testcase passing locally. Failed due to minor setup issue.
Screenshot 2022-05-07 at 12 23 06 AM

**Review by abhimutant — APPROVED** [review]

**Review by siddharth-kulshrestha — APPROVED** [review]
LGTM

**Pull request merged**
