### PR TITLE
Added singular and plural datasources for service groups with test cases

### LINKED ISSUE #353: Datasources for service groups along with test cases
**Is your feature request related to a problem? Please describe.**
Support for datasource service group (with plural) is missing. This ticket is created to track it.

**Describe the solution you'd like**
Add datasource for service groups and relevant test cases for testing linking of network security rules.

**Describe alternatives you've considered**

**Additional context**
Since we have already added resource group for address group and service group in release v1.3.0 in [this PR](https://github.com/nutanix/terraform-provider-nutanix/pull/322) against issue #170 . 
[This PR](https://github.com/nutanix/terraform-provider-nutanix/pull/345) adds the support of linking service group and address groups to network security rules.

### PR DESCRIPTION
**Pull request by siddharth-kulshrestha**
Fix for the issue #353

### CODE REVIEW

**Comment by siddharth-nutanix** [comment]
/ok-to-test
>Acceptance test run status: failure
>

**Comment by siddharth-nutanix** [comment]
/ok-to-test
>Acceptance test run status: failure
>

**Comment by siddharth-nutanix** [comment]
/ok-to-test
>Acceptance test run status: failure
>

**Comment by siddharth-nutanix** [comment]
/ok-to-test
>Acceptance test run status: success
>Line code coverage is 59.6

**Review by bhati-pradeep — APPROVED** [review]

**Review by siddharth-nutanix — APPROVED** [review]

**Pull request merged**
