### PR TITLE
Fix to only use assigned IP addresses

### PR DESCRIPTION
**Pull request by GBrawl**
Fix for #205 

Only adds the assigned IP addresses to the state and not the "LEARNED" ones. Running "terraform apply" now doesn't give an error.

### CODE REVIEW

**Comment by JonKohler** [comment]
Thanks @GBrawl ! ill have marin/tony take a double check, but seems straight forward to me

**Comment by BartJoris** [comment]
This fix works fine for me, thanks @Gbrawl!

**Comment by JonKohler** [comment]
I see you pushed an additional commit @GBrawl - are you ready for this to be merged as-is? 

Also, I see travis is being silly about the unit tests, likely a travis issue, have you tried the unit tests locally?

**Comment by JonKohler** [comment]
Actually, this is straight forward enough for a merge as is, given this is landing in develop, we can easily pull it out if it doesn't pass the next develop unit test run

**Pull request merged**
