### PR TITLE
Change default node pool names for karbon cluster creation

### LINKED ISSUE #373: Karbon 2.4 Cluster creation failing
### Nutanix Cluster Information
Nutanix Karbon 2.4
### Affected Resource(s)

* nutanix_karbon_cluster
### Terraform Configuration Files
Standard Karbon creation. See Karbon examples
### Debug Output
│ Error: error occurred during cluster creation:
│  error: name in body should match '^[a-z0-9]([-a-z0-9]*[a-z0-9])?$'
│
### Expected Behavior
Karbon cluster should be created without an error
### Actual Behavior
Error regarding name regex is thrown
### Steps to Reproduce

1. Define a Karbon cluster in TF
2. TF apply
### Important Factors
Only occurs in Karbon 2.4. Issues is related to default node pool names used.
As a workaround pass the name attribute on a per nodepool basis in TF.
​

### PR DESCRIPTION
**Pull request by siddharth-nutanix**

### CODE REVIEW

**Comment by siddharth-nutanix** [comment]
/ok-to-test
>Acceptance test run status: failure
>

**Comment by siddharth-nutanix** [comment]
/ok-to-test
>Acceptance test run status: failure
>

**Comment by bhati-pradeep** [comment]
/ok-to-test
>Acceptance test run status: failure
>

**Comment by bhati-pradeep** [comment]
/ok-to-test
>Acceptance test run status: success
>Line code coverage is 59.9

**Pull request merged**
