### PR TITLE
Add num_queues parameter for virtual machine NICs

### PR DESCRIPTION
**Pull request by ckhordiasma**
implemented num_queues option for nics in nutanix_virtual_machine
objects. If num_queues is changed for an existing nic, the VM will be
restarted. If a new nic is added to a VM with a queue number specified,
the VM will not be restarted.

If any nic parameters besides num_queues are changed, the VM should not
restart.

Also added some lines in the test file, I did not put in much because the tests were not working for me (tests would pass no matter what I added)

### CODE REVIEW

**Comment by siddharth-nutanix** [comment]
@ckhordiasma Can you pull latest master and resolve conflicts ?

**Comment by siddharth-nutanix** [comment]
@ckhordiasma 
Please resolve the conflicts and rebase with master.

**Comment by ckhordiasma** [comment]
Hello, will get this done by the end of the week. Sorry for the delay

**Comment by siddharth-nutanix** [comment]
/ok-to-test
>Acceptance test run status: failure
>

**Comment by siddharth-nutanix** [comment]
@ckhordiasma Please check 
https://github.com/nutanix/terraform-provider-nutanix/runs/5354524381?check_suite_focus=true

`TestAccNutanixVirtualMachine_WithSubnet ` test case has failed.

**Comment by siddharth-nutanix** [comment]
/ok-to-test
>Acceptance test run status: failure
>

**Comment by ckhordiasma** [comment]
when I run `make fmt` or `make fmtcheck` locally, it doesn't flag me with formatting issues of my code. Is there some other dependency I need?

**Comment by siddharth-kulshrestha** [comment]
> when I run `make fmt` or `make fmtcheck` locally, it doesn't flag me with formatting issues of my code. Is there some other dependency I need?

make lint

**Comment by siddharth-nutanix** [comment]
/ok-to-test
>Acceptance test run status: failure
>

**Review by abhimutant — APPROVED** [review]
Merging it to a different branch to check

**Comment by siddharth-nutanix** [comment]
/ok-to-test
>Acceptance test run status: failure
>

**Comment by bhati-pradeep** [comment]
Closing this PR, as  #385 merged with this above commits.

**Pull request closed without merging**
