### PR TITLE
add hashicorp check scripts and modify GNUMakefile and travis

### PR DESCRIPTION
**Pull request by marinsalinas**

### CODE REVIEW

**Comment by cgriggs01** [comment]
👍

**Comment by thetonymaster** [comment]
LGTM, what about you @JonKohler

**Comment by thetonymaster** [comment]
Probably just install dep in the travis file

**Comment by thetonymaster** [comment]
otherwise lgtm

**Comment by thetonymaster** [comment]
`curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh`

**Comment by marinsalinas** [comment]
I've installed `de`p but I got dependencies errors but these are because this project was developed as if it were in the official `terraform-providers` repo on GitHub. Travis will work after migration.

**Comment by JonKohler** [comment]
Merged this @cgriggs01 @bill-rich - marching forward!

**Pull request merged**
