### PR TITLE
handling the error

### PR DESCRIPTION
**Pull request by Abhishekism9450**
Added the error in List API call.

### CODE REVIEW

**Comment by abhimutant** [comment]
/ok-to-test era
>Acceptance test run status: failure
>Current line coverage (12.2) is below threshold (50). Kindly add more acceptance tests.

**Comment by abhimutant** [comment]
/ok-to-test era
>Acceptance test run status: failure
>Current line coverage (15.9) is below threshold (50). Kindly add more acceptance tests.

**Comment by abhimutant** [comment]
/ok-to-test era
>Acceptance test run status: failure
>Current line coverage (15.8) is below threshold (50). Kindly add more acceptance tests.

**Comment by abhimutant** [comment]
/ok-to-test era
>Acceptance test run status: failure
>Current line coverage (15.9) is below threshold (50). Kindly add more acceptance tests.

**Review by abhimutant — APPROVED** [review]

**Review by bhati-pradeep — APPROVED** [review]
LGTM, Please add in docs this change.

**Pull request merged**
