### PR TITLE
Feat/1.8.1

### PR DESCRIPTION
**Pull request by Abhishekism9450**
- NDB Improvements and fixes 
       - datasource for network available ips
       - imports on day2 actions
       - error check in datasource for ndb cluster
       - clone lcm fix
       - nil check for d.id() in ReadContext

### CODE REVIEW

**Comment by abhimutant** [comment]
/ok-to-test era
>Acceptance test run status: failure
>Current line coverage (17.7) is below threshold (50). Kindly add more acceptance tests.

**Comment by abhimutant** [comment]
/ok-to-test era
>Acceptance test run status: failure
>Current line coverage (17.5) is below threshold (50). Kindly add more acceptance tests.

**Comment by abhimutant** [comment]
/ok-to-test era
>Acceptance test run status: failure
>Current line coverage (18.0) is below threshold (50). Kindly add more acceptance tests.

**Comment by abhimutant** [comment]
/ok-to-test era
>Acceptance test run status: failure
>Current line coverage (18.0) is below threshold (50). Kindly add more acceptance tests.

**Review by siddharth-kulshrestha — APPROVED** [review]

**Review by bhati-pradeep — APPROVED** [review]

**Review by siddharth-kulshrestha — APPROVED** [review]

**Review by abhimutant — APPROVED** [review]

**Pull request merged**
