### PR TITLE
Add support for mapstructure decode tag for reusability

### PR DESCRIPTION
**Pull request by JRemitz**
I would like to leverage the client v3 API structs for Packer objects to the Nutanix API server. This would require adding support for [mapstructure](https://github.com/mitchellh/mapstructure) based on [Packer's documentation](https://www.packer.io/docs/extending/custom-builders.html#the-quot-prepare-quot-method) to simplify the process of parsing the Packer config.

I currently have [**Packer PR 8175**](https://github.com/hashicorp/packer/pull/8175) open to add support for Nutanix - any help/insight to align projects would be greatly appreciated!

This includes changes from #80 along with corresponding `mapstructure` tags.

### CODE REVIEW

**Comment by marinsalinas** [comment]
@JRemitz  could you update with the latest code from master?

**Comment by JRemitz** [comment]
I can and will take a look at this in a bit.

**Comment by JRemitz** [comment]
@marinsalinas - I've updated however I see that the linter is failing on some of the long lines due to the extended tags. What's the best way to break those down?

**Comment by marinsalinas** [comment]
@JRemitz, for now, you can add this into https://github.com/terraform-providers/terraform-provider-nutanix/blob/master/.golangci.yml configuration. See: https://github.com/golangci/golangci-lint/blob/a85e1e1faaef7f2f6a091e9b93df6be09539a009/.golangci.example.yml#L207

**Comment by JRemitz** [comment]
@marinsalinas - apologies for the delay but finally got around to "fixing" this. Please take a look and let me know what you think. Thanks!

**Review by marinsalinas — CHANGES_REQUESTED** [review]
Just resolve conflicts with go.mod

**Comment by JRemitz** [comment]
Merged - how about now, @marinsalinas ?

**Review by marinsalinas — APPROVED** [review]

**Pull request merged**
