### PR TITLE
fix issue with vm.GuestCustomization not being initialized

### PR DESCRIPTION
**Pull request by htj**
Note, that there are similar issues further down in the file.

### CODE REVIEW

**Comment by JonKohler** [comment]
Thanks @htj !! LGTM, I merged this directly into master. In the future - target your PR's to the develop branch

**Comment by htj** [comment]
Will do :-)

**Comment by htj** [comment]
Any chance this could be merged into the devel branch as well?

It people base their commits on master, merging into development is rather messy if it not kept up to date with master.

**Comment by JonKohler** [comment]
yes, i asked the guys to do this and we;ll clean it up! :)

**Pull request merged**
