### PR TITLE
Feat/1.9.0

### PR DESCRIPTION
**Pull request by Abhishekism9450**
Newly added Resource:
- karbon worker nodepool 

Improvements:

- vlan id 0 should be supported.
- timeouts for karbon cluster resource
- NBD schema validation

### CODE REVIEW

**Comment by abhimutant** [comment]
/ok-to-test pc
>Acceptance test run status: failure
>Current line coverage (31.0) is below threshold (50). Kindly add more acceptance tests.

**Comment by abhimutant** [comment]
/ok-to-test pc
>Acceptance test run status: failure
>Current line coverage (28.2) is below threshold (50). Kindly add more acceptance tests.

**Comment by abhimutant** [comment]
/ok-to-test pc
>Acceptance test run status: failure
>Current line coverage (30.7) is below threshold (50). Kindly add more acceptance tests.

**Comment by abhimutant** [comment]
/ok-to-test karbon
>Acceptance test run status: failure
>Current line coverage (4.5) is below threshold (50). Kindly add more acceptance tests.

**Comment by abhimutant** [comment]
/ok-to-test karbon
>Acceptance test run status: failure
>Current line coverage (4.5) is below threshold (50). Kindly add more acceptance tests.

**Comment by abhimutant** [comment]
/ok-to-test pc
>Acceptance test run status: failure
>Current line coverage (30.7) is below threshold (50). Kindly add more acceptance tests.

**Comment by abhimutant** [comment]
/ok-to-test karbon
>Acceptance test run status: failure
>Current line coverage (5.9) is below threshold (50). Kindly add more acceptance tests.

**Comment by abhimutant** [comment]
/ok-to-test karbon
>Acceptance test run status: failure
>Current line coverage (0.0) is below threshold (50). Kindly add more acceptance tests.

**Comment by abhimutant** [comment]
/ok-to-test karbon
>Acceptance test run status: success
>Current line coverage (5.9) is below threshold (50). Kindly add more acceptance tests.

**Comment by abhimutant** [comment]
/ok-to-test karbon
>Acceptance test run status: failure
>Current line coverage (5.8) is below threshold (50). Kindly add more acceptance tests.

**Comment by abhimutant** [comment]
/ok-to-test karbon
>Acceptance test run status: failure
>Current line coverage (5.2) is below threshold (50). Kindly add more acceptance tests.

**Comment by abhimutant** [comment]
/ok-to-test karbon
>Acceptance test run status: success
>Current line coverage (6.0) is below threshold (50). Kindly add more acceptance tests.

**Comment by abhimutant** [comment]
/ok-to-test pc
>Acceptance test run status: failure
>Current line coverage (30.9) is below threshold (50). Kindly add more acceptance tests.

**Comment by abhimutant** [comment]
/ok-to-test karbon
>Acceptance test run status: success
>Current line coverage (6.0) is below threshold (50). Kindly add more acceptance tests.

**Review by siddharth-kulshrestha — APPROVED** [review]

**Review by bhati-pradeep — APPROVED** [review]
LGTM

**Pull request merged**
