### PR TITLE
correcting example

### PR DESCRIPTION
**Pull request by olljanat**
Closes https://github.com/nutanix/terraform-provider-nutanix/issues/216

### CODE REVIEW

**Review by marinsalinas — APPROVED** [review]
LGTM!

Also, the image_uri is getting some errors when you are testing on GCP, because it can't reach the iso file.

@JonKohler, Do we have a public iso image to add to the example?

**Comment by olljanat** [comment]
Is http://download.cirros-cloud.net/0.3.4/cirros-0.3.4-x86_64-disk.img actually same than which you have on example now?

**Comment by JonKohler** [comment]
Opened https://github.com/terraform-providers/terraform-provider-nutanix/issues/9 to cover this, this will address when done #9

**Comment by olljanat** [comment]
@JonKohler / @marinsalinas what is the plan with this project now? Why not even this kind of minor things gets merged?

**Pull request merged**
