### PR TITLE
setting machine type in update context

### PR DESCRIPTION
**Pull request by Abhishekism9450**
fix with examples. 

issue : #494 , #622

### CODE REVIEW

**Review by siddharth-kulshrestha — APPROVED** [review]

**Comment by abhimutant** [comment]
/ok-to-test pc
>Acceptance test run status: failure
>Current line coverage (30.7) is below threshold (50). Kindly add more acceptance tests.

**Comment by abhimutant** [comment]
/ok-to-test pc

>Acceptance test run status: failure
>Current line coverage (31.0) is below threshold (50). Kindly add more acceptance tests.

**Pull request merged**
